services:
  - type: web
    name: htool-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: sql303.ezyro.com
      - key: DB_USER
        value: ezyro_42627914
      - key: DB_PASS
        value: Hunghai443@#
      - key: DB_NAME
        value: ezyro_42627914_htool_keys
